[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "    [%(asctime)s - %(filename)30s:%(lineno)4s - %(levelname)5s - %(funcName)30s()]\n%(message)s\n"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
